// World's Top 30 Most Venomous Snakes Dataset
// Curated with tiered lethality star ratings: 5-Star (1 min), 4-Star (3 min), 3-Star (5 min)
// Includes sarcastic second-bite advice for lower-tier venomous snakes!

const SNAKES_DATA = [
  // ==================== 5-STAR DEADLY SNAKES (1 MINUTE / 60 SECONDS TO DIE) ====================
  {
    id: "inland_taipan",
    name: "Inland Taipan",
    scientificName: "Oxyuranus microlepidotus",
    nickname: "The Introverted God of Lethality",
    primaryColor: "brown",
    colorCategory: "brown",
    colorDescription: "Dark tan to olive-brown with seasonal changes (darker in winter, pale in summer)",
    spot: "desert",
    spotDescription: "Deep clay cracks and fissures in Queensland/South Australia desert pans",
    region: "Australia (Inland Outback)",
    ld50: "0.025 mg/kg (Most toxic venom on planet Earth)",
    venomType: "Neurotoxin, Procoagulant, Myotoxin, Hyaluronidase",
    threatLevel: 5,
    countdownSeconds: 60,
    clinicalSurvival: "30 to 45 minutes untreated (Single bite can kill 100 adult humans)",
    sarcasticQuote: "A single drop can kill 100 grown adults. Fortunately, it lives in the middle of nowhere and hates social interaction just like you.",
    sarcasticAdvice: "Good news: Almost nobody gets bitten by this because it avoids humans. Bad news: You managed to find one, which means your survival instincts are statistically sub-zero.",
    secondBiteAdvice: "5-Star Doom: One bite delivers enough neurotoxin to exterminate an entire auditorium. A second bite is completely redundant.",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Mild confusion. Why did you reach into a clay crevice in the outback?" },
      { pct: 0.65, text: "Stage 2: Coagulation breakdown. Your blood is turning into raspberry gelatin." },
      { pct: 0.40, text: "Stage 3: Neuro-paralysis. Breathing is now an optional background activity." },
      { pct: 0.15, text: "Stage 4: Your life flashes before your eyes. Mostly just you staring at your phone." },
      { pct: 0.03, text: "Stage 5: Wave goodbye to the desert dingoes." }
    ],
    avatarColor: "#8d6e63"
  },
  {
    id: "eastern_brown",
    name: "Eastern Brown Snake",
    scientificName: "Pseudonaja textilis",
    nickname: "Suburban Lawn Assassin",
    primaryColor: "brown",
    colorCategory: "brown",
    colorDescription: "Uniform pale to dark brown, yellowish underbelly with orange freckles",
    spot: "grass",
    spotDescription: "Suburban backyards, golf courses, compost bins, tall agricultural grass",
    region: "Eastern Australia",
    ld50: "0.053 mg/kg (#2 most toxic terrestrial snake)",
    venomType: "Potent Presynaptic & Postsynaptic Neurotoxins, Procoagulants",
    threatLevel: 5,
    countdownSeconds: 60,
    clinicalSurvival: "15 to 30 minutes without immediate compression (collapses in minutes)",
    sarcasticQuote: "It loves suburbs, moves at supersonic speed, and gets angry if you look at it with poor posture.",
    sarcasticAdvice: "You were probably trying to mow the lawn or look for a lost tennis ball. Now your main job is lying completely motionless while contemplating your existence.",
    secondBiteAdvice: "5-Star Lethality: First bite already deployed weaponized procoagulants. No second bite required.",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Sudden dizzy spell. No, it was not the heatwave." },
      { pct: 0.65, text: "Stage 2: Sudden drop in blood pressure. The couch looks very far away." },
      { pct: 0.40, text: "Stage 3: Venom-induced consumption coagulopathy. Science words for not great." },
      { pct: 0.15, text: "Stage 4: Please tell your lawnmower we said goodbye." },
      { pct: 0.03, text: "Stage 5: The kangaroos will inherit your estate." }
    ],
    avatarColor: "#5d4037"
  },
  {
    id: "coastal_taipan",
    name: "Coastal Taipan",
    scientificName: "Oxyuranus scutellatus",
    nickname: "The 6-Foot Lightning Rod",
    primaryColor: "brown",
    colorCategory: "brown",
    colorDescription: "Light olive to russet reddish-brown, pale cream snout, slender coffin head",
    spot: "grass",
    spotDescription: "Sugar cane fields, coastal eucalyptus scrub, overgrown farm sheds",
    region: "Northern & Eastern Coastal Australia, New Guinea",
    ld50: "0.099 mg/kg (#3 terrestrial toxic)",
    venomType: "Taipoxin (destroyer of motor nerve terminals), Myotoxins",
    threatLevel: 5,
    countdownSeconds: 60,
    clinicalSurvival: "30 minutes untreated (100% fatal without antivenom historically)",
    sarcasticQuote: "Possesses 12mm fangs and strikes up to several times before your slow human brain registers pain.",
    sarcasticAdvice: "Do not attempt to run. It strikes faster than your WiFi disconnects during a Zoom call.",
    secondBiteAdvice: "5-Star Striker: It strikes multiple times by default anyway. You already received the VIP bundle.",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Headaches and nausea. You thought it was caffeine withdrawal." },
      { pct: 0.65, text: "Stage 2: Complete cranial nerve paralysis. Smiling is now physically impossible." },
      { pct: 0.40, text: "Stage 3: Massive internal micro-haemorrhaging. Lovely." },
      { pct: 0.15, text: "Stage 4: Your lungs have submitted a two-week notice effective immediately." },
      { pct: 0.03, text: "Stage 5: Welp. See ya on the other side." }
    ],
    avatarColor: "#6d4c41"
  },
  {
    id: "many_banded_krait",
    name: "Many-Banded Krait",
    scientificName: "Bungarus multicinctus",
    nickname: "The Monochrome Sleeper Agent",
    primaryColor: "banded",
    colorCategory: "banded",
    colorDescription: "Glossy black with 30-50 stark crisp white alternating bands",
    spot: "water",
    spotDescription: "Paddy fields, riverbanks, drainage ditches, wet agricultural wetlands",
    region: "Southern China, Taiwan, Southeast Asia",
    ld50: "0.09 mg/kg (Highest toxicity in mainland Asia)",
    venomType: "Alpha & Beta Bungarotoxin (Blockade of neuromuscular junction)",
    threatLevel: 5,
    countdownSeconds: 60,
    clinicalSurvival: "1 to 2 hours painless lethality (often fatal without mechanical ventilation)",
    sarcasticQuote: "Its bite barely hurts at all. You will think, Oh nice, just a gentle scratch! That is the trap.",
    sarcasticAdvice: "A bite so painless you might sleep through it. Unfortunately, you also will not wake up from it.",
    secondBiteAdvice: "5-Star Bungarotoxin: The neuromuscular blockade is already sealed. No refill needed.",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Hey, that did not hurt at all! I am fine! (Narrator: They were not fine)." },
      { pct: 0.65, text: "Stage 2: Ptosis sets in. Your eyelids feel like 50-pound dumbbells." },
      { pct: 0.40, text: "Stage 3: Loss of swallowing reflex. Drooling like an overtired toddler." },
      { pct: 0.15, text: "Stage 4: Total flaccid paralysis. You are now a human sandbag." },
      { pct: 0.03, text: "Stage 5: Goodnight, sweet prince." }
    ],
    avatarColor: "#212121"
  },
  {
    id: "black_mamba",
    name: "Black Mamba",
    scientificName: "Dendroaspis polylepis",
    nickname: "The 12 MPH Death Train",
    primaryColor: "black",
    colorCategory: "black",
    colorDescription: "Matte gunmetal-grey to dark olive-brown; named for its pitch-black mouth lining",
    spot: "tree",
    spotDescription: "Rocky kopjes, savannah bush, termite mounds, occasionally dropping from trees",
    region: "Sub-Saharan Africa",
    ld50: "0.28 mg/kg (100% untreated fatality rate in under 30 mins)",
    venomType: "Dendrotoxins (Cardiotoxin + Neurotoxin causing systemic shutdown)",
    threatLevel: 5,
    countdownSeconds: 60,
    clinicalSurvival: "15 to 30 minutes without antivenom (can collapse in 10 minutes)",
    sarcasticQuote: "It can slither at 12 mph, rears up to your chest level, and the inside of its mouth is the exact shade of your future.",
    sarcasticAdvice: "If you see it gaping its black mouth, you have already made four fatal lifestyle decisions.",
    secondBiteAdvice: "5-Star Maximum Lethality: 60 seconds is all you get. A second bite is completely gratuitous overkill.",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Metallic taste in your mouth and tingling skin. Pure dread follows." },
      { pct: 0.65, text: "Stage 2: Excessive salivation and sweating. You look like you did an intense cardio session." },
      { pct: 0.40, text: "Stage 3: Respiratory collapse begins. Who needed oxygen anyway?" },
      { pct: 0.15, text: "Stage 4: Rapid cardiac arrhythmia. Your heart is playing techno beats." },
      { pct: 0.03, text: "Stage 5: Final boarding call for flight AFTERLIFE-001." }
    ],
    avatarColor: "#1a1a1a"
  },
  {
    id: "boomslang",
    name: "Boomslang",
    scientificName: "Dispholidus typus",
    nickname: "The Disciplinary Branch",
    primaryColor: "green",
    colorCategory: "green",
    colorDescription: "Bright vivid emerald green (males) or dull brown (females), huge green eyes",
    spot: "tree",
    spotDescription: "Acacia trees, thick bushes, hanging motionless like a harmless branch",
    region: "Sub-Saharan Africa",
    ld50: "0.1 mg/kg (Slow-acting catastrophic hemotoxin)",
    venomType: "Potent Hemotoxin destroying platelets and fibrinogen",
    threatLevel: 5,
    countdownSeconds: 60,
    clinicalSurvival: "Hours to 24 hours of systematic internal hemorrhaging",
    sarcasticQuote: "Looks like a cute cartoon tree snake with giant anime eyes. Will literally make you bleed from your fingernails.",
    sarcasticAdvice: "Do not touch branches that have eyeballs. We should not even have to write this down.",
    secondBiteAdvice: "5-Star Hemotoxin: Your fibrinogen is already zero. Begging for a second bite won't make you bleed any harder.",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Aww look at that branch with anime eyes!" },
      { pct: 0.65, text: "Stage 2: Nose starts bleeding. Then gums. Then old scrape wounds reopen." },
      { pct: 0.40, text: "Stage 3: You are now a leaky fountain of red regret." },
      { pct: 0.15, text: "Stage 4: Fibrinogen count: 0. Clotting ability: -100." },
      { pct: 0.03, text: "Stage 5: Bye bye. Watch out for branches next time." }
    ],
    avatarColor: "#2e7d32"
  },
  {
    id: "russells_viper",
    name: "Russell's Viper",
    scientificName: "Daboia russelii",
    nickname: "The Kidney Collector",
    primaryColor: "brown",
    colorCategory: "brown",
    colorDescription: "Deep golden-brown with three longitudinal rows of dark brown oval spots",
    spot: "grass",
    spotDescription: "Paddy fields, village outskirts, grain storage sheds, tall grass",
    region: "Indian Subcontinent & Southeast Asia",
    ld50: "0.16 mg/kg (Responsible for majority of Asian snakebite fatalities)",
    venomType: "Complex Hemotoxin, Coagulant, Cytotoxin, Renal Toxin",
    threatLevel: 5,
    countdownSeconds: 60,
    clinicalSurvival: "Severe shock within 20 mins; acute renal failure within hours",
    sarcasticQuote: "Hisses so loud it sounds like an exploding pressure cooker. If you hear it, it is already too late.",
    sarcasticAdvice: "Causes acute kidney failure and necrosis. Say nice things to your kidneys while they are still clocking in.",
    secondBiteAdvice: "5-Star Viper: Enough venom was delivered to bankrupt all your internal organs in 60 seconds.",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Hissing like a tea kettle. Extreme localized blistering pain." },
      { pct: 0.65, text: "Stage 2: Severe systemic swelling and spontaneous gum bleeding." },
      { pct: 0.40, text: "Stage 3: Kidneys have officially filed for chapter 11 bankruptcy." },
      { pct: 0.15, text: "Stage 4: Pituitary gland necrosis. Medical textbooks will study this." },
      { pct: 0.03, text: "Stage 5: The pressure cooker has exploded." }
    ],
    avatarColor: "#795548"
  },
  {
    id: "saw_scaled_viper",
    name: "Saw-Scaled Viper",
    scientificName: "Echis carinatus",
    nickname: "The Spicy Maraca",
    primaryColor: "brown",
    colorCategory: "brown",
    colorDescription: "Sandy grey-brown with pale zigzag dorsal patches and cross marks on head",
    spot: "rocks",
    spotDescription: "Dry scrubland, rock piles, mud brick walls, under loose stones at night",
    region: "Middle East, Central Asia, India",
    ld50: "0.24 mg/kg (Responsible for more deaths globally than any other snake)",
    venomType: "Ecarin prothrombin activator, massive internal coagulopathy",
    threatLevel: 5,
    countdownSeconds: 60,
    clinicalSurvival: "Rapid localized destruction followed by slow hemorrhagic collapse",
    sarcasticQuote: "Rubs its serrated scales together to make a sizzling noise like bacon in a frying pan. You are the bacon.",
    sarcasticAdvice: "Small, angry, and has the world record for human body counts. Respect the angry shoe-lace.",
    secondBiteAdvice: "5-Star Global Champion: Has the world record for body counts. 60 seconds is all it takes.",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Sizzling scale sounds. Why does the ground sound like fajitas?" },
      { pct: 0.65, text: "Stage 2: Rapid strike. Barely 18 inches long but possesses the rage of a dying star." },
      { pct: 0.40, text: "Stage 3: Extensive tissue necrosis and systemic blood thinning." },
      { pct: 0.15, text: "Stage 4: You will definitely not be winning any sprinting medals today." },
      { pct: 0.03, text: "Stage 5: The spicy maraca wins again." }
    ],
    avatarColor: "#8d6e63"
  },
  {
    id: "king_cobra",
    name: "King Cobra",
    scientificName: "Ophiophagus hannah",
    nickname: "His Imperial Majesty of Doom",
    primaryColor: "green",
    colorCategory: "green",
    colorDescription: "Olive-green, bronze, or yellowish-brown with pale yellow chevron crossbands",
    spot: "tree",
    spotDescription: "Dense bamboo thickets, mangrove swamps, highland rainforests, near agricultural streams",
    region: "South and Southeast Asia",
    ld50: "1.28 mg/kg (Venom volume: up to 1,000 mg - can kill an adult Asian elephant in 3 hours)",
    venomType: "High-volume Neurotoxins (Hannahtoxin) & Cytotoxins",
    threatLevel: 5,
    countdownSeconds: 60,
    clinicalSurvival: "15 to 30 minutes for human collapse due to sheer venom volume",
    sarcasticQuote: "It stands 6 feet tall, looks you directly in the eye, and eats other venomous snakes for breakfast.",
    sarcasticAdvice: "When a snake looks down at you from eye level, negotiations have already failed.",
    secondBiteAdvice: "5-Star Monarchy: It already gave you 7ml of venom. A second bite would just spill on your shirt.",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: A 14-foot snake is standing up looking at you like an angry school principal." },
      { pct: 0.65, text: "Stage 2: Up to 7ml of venom injected. That is not a bite, that is a beverage." },
      { pct: 0.40, text: "Stage 3: Deep low-frequency growl vibrating in your chest. Pure dread." },
      { pct: 0.15, text: "Stage 4: Central nervous system shuts down like a Windows 95 desktop." },
      { pct: 0.03, text: "Stage 5: Long live the King." }
    ],
    avatarColor: "#33691e"
  },
  {
    id: "dubois_sea_snake",
    name: "Dubois' Sea Snake",
    scientificName: "Aipysurus duboisii",
    nickname: "Reef Reaper",
    primaryColor: "banded",
    colorCategory: "banded",
    colorDescription: "Pale brownish-yellow with dark brown patches and broad paddle tail",
    spot: "water",
    spotDescription: "Coral reef flats, seaweed beds at depths of 20 to 80 meters",
    region: "Coral Sea, Arafura Sea, Timor Sea",
    ld50: "0.044 mg/kg (Highest verified toxicity among all sea snakes)",
    venomType: "Postsynaptic neurotoxin + massive myotoxin",
    threatLevel: 5,
    countdownSeconds: 60,
    clinicalSurvival: "30 minutes without hyperbaric antivenom intervention",
    sarcasticQuote: "Scientific studies confirmed it is the most toxic sea snake in the world. You had to go snorkeling, did not you?",
    sarcasticAdvice: "Do not attempt to pet sea cucumbers or friendly underwater ropes.",
    secondBiteAdvice: "5-Star Marine Lethality: 60 seconds before your soul descends into the reef trench.",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Tiny scratch mark. You thought you scraped a sea fan." },
      { pct: 0.65, text: "Stage 2: Total limb heaviness. Swimming suddenly requires 1000% more effort." },
      { pct: 0.40, text: "Stage 3: Severe lockjaw and diaphragm collapse." },
      { pct: 0.15, text: "Stage 4: Sinking down into Davy Jones locker." },
      { pct: 0.03, text: "Stage 5: Poseidon has claimed another victim." }
    ],
    avatarColor: "#bcaaa4"
  },
  {
    id: "gaboon_viper",
    name: "Gaboon Viper",
    scientificName: "Bitis gabonica",
    nickname: "The 2-Inch Needle Chonker",
    primaryColor: "grey",
    colorCategory: "grey",
    colorDescription: "Geometric carpet camouflage of purple, pastel pink, buff, and velvety brown with horns",
    spot: "rocks",
    spotDescription: "Rainforest floor leaf litter, under decaying logs in Central/West Africa",
    region: "Central, West, and East Africa",
    ld50: "0.8 mg/kg (Possesses 2.0-inch (5cm) fangs - longest fangs of any venomous snake!)",
    venomType: "Cardiotoxin, Hemotoxin, massive tissue-destroying proteases",
    threatLevel: 5,
    countdownSeconds: 60,
    clinicalSurvival: "15 to 45 minutes; massive venom dose injected straight into deep muscle",
    sarcasticQuote: "Has two-inch fangs. That is not a snake bite, that is a double hypodermic harpoon assault.",
    sarcasticAdvice: "It looks like a Persian rug on the forest floor. Do not step on the spicy Persian rug.",
    secondBiteAdvice: "5-Star Fangs: Two-inch needles already injected straight into bone marrow. 60 seconds is plenty.",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Two-inch needles penetrate straight into bone and deep muscle." },
      { pct: 0.65, text: "Stage 2: Over 500mg of cardiotoxins flood your circulation." },
      { pct: 0.40, text: "Stage 3: Acute myocardial damage. Heart stops pumping coherent rhythm." },
      { pct: 0.15, text: "Stage 4: Profound internal hemorrhaging. Consciousness slips away." },
      { pct: 0.03, text: "Stage 5: The Persian rug strikes back." }
    ],
    avatarColor: "#455a64"
  },
  {
    id: "belchers_sea_snake",
    name: "Belcher's Sea Snake",
    scientificName: "Hydrophis belcheri",
    nickname: "The Pelagic Nuke",
    primaryColor: "yellow",
    colorCategory: "yellow",
    colorDescription: "Pale yellow or chrome yellow with dark green-grey crossbands and paddle tail",
    spot: "water",
    spotDescription: "Tropical coral reefs, shallow continental shelves, Indo-Pacific waters",
    region: "Indian Ocean, Gulf of Thailand, New Guinea",
    ld50: "0.24 mg/kg (Legendary extreme marine toxicity)",
    venomType: "Myotoxins & Presynaptic Neurotoxins",
    threatLevel: 5,
    countdownSeconds: 60,
    clinicalSurvival: "30 minutes to a few hours while drowning in deep water",
    sarcasticQuote: "It usually has a docile temperament, which means you really had to work hard to annoy it while scuba diving.",
    sarcasticAdvice: "Swimming away is futile. It is a fish with fangs. You are an awkward monkey with rubber flippers.",
    secondBiteAdvice: "5-Star Marine Toxin: Milligrams of pure myotoxins are already dissolving your muscle cells.",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Puncture mark on your toe underwater. Was that coral or doom?" },
      { pct: 0.65, text: "Stage 2: Myoglobinuria kicks in. Severe muscle aching throughout your body." },
      { pct: 0.40, text: "Stage 3: Swallowing and breathing shut down. At least you are already wet." },
      { pct: 0.15, text: "Stage 4: Deep sea sirens calling your name." },
      { pct: 0.03, text: "Stage 5: SpongeBob sends his regards." }
    ],
    avatarColor: "#fbc02d"
  },

  // ==================== 4-STAR DEADLY SNAKES (3 MINUTES / 180 SECONDS TO DIE) ====================
  {
    id: "tiger_snake",
    name: "Mainland Tiger Snake",
    scientificName: "Notechis scutatus",
    nickname: "The Stripey Tasmanian Terror",
    primaryColor: "banded",
    colorCategory: "banded",
    colorDescription: "Olive, yellow, and brown alternating bands; can be solid jet black in southern islands",
    spot: "water",
    spotDescription: "Creek beds, dams, swamps, river edges, tall reeds, coastal dunes",
    region: "Southern Australia and Tasmania",
    ld50: "0.12 mg/kg (Devastating Australian cocktail)",
    venomType: "Potent Myotoxins, Coagulants, Neurotoxins, Hemolysins",
    threatLevel: 4,
    countdownSeconds: 180,
    clinicalSurvival: "30 to 60 minutes untreated (muscle breakdown ruins kidneys)",
    sarcasticQuote: "Flattens its neck like a pancake when annoyed. It is always annoyed.",
    sarcasticAdvice: "If you are walking near a creek in Melbourne and see striped spaghetti, walk the other way.",
    secondBiteAdvice: "⚠️ 4-Star Venom Delay: This snake grants you 3 whole minutes to think about your mistakes. If you're in a rush to meet your ancestors, poke it again so the rest of the poison gets released!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Local pain in your foot. Sudden numbness in your lips." },
      { pct: 0.65, text: "Stage 2: Myolysis breaks down your muscles. Your urine turns dark brown." },
      { pct: 0.40, text: "Stage 3: Double vision. Now you see two tiger snakes! Twice the horror!" },
      { pct: 0.15, text: "Stage 4: Diaphragm paralysis. Inhale... wait, you cannot." },
      { pct: 0.03, text: "Stage 5: Australia strikes again, mate." }
    ],
    avatarColor: "#424242"
  },
  {
    id: "death_adder",
    name: "Common Death Adder",
    scientificName: "Acanthophis antarcticus",
    nickname: "The 0.15-Second Landmine",
    primaryColor: "grey",
    colorCategory: "grey",
    colorDescription: "Banded grey, reddish-brown, and pale charcoal with a worm-like yellow tail tip",
    spot: "rocks",
    spotDescription: "Buried under leaf litter, sandy soil, loose gravel along hiking trails",
    region: "Eastern and Southern Australia",
    ld50: "0.4 mg/kg (Fastest strike speed on Earth: 0.13 seconds)",
    venomType: "Postsynaptic Neurotoxins causing flaccid paralysis",
    threatLevel: 4,
    countdownSeconds: 180,
    clinicalSurvival: "1 to 6 hours untreated (causes rapid respiratory arrest)",
    sarcasticQuote: "Wiggles the tip of its tail to look like a delicious caterpillar. You fell for caterpillar bait.",
    sarcasticAdvice: "It does not bother slithering away when you walk by. It sits there like a landmine waiting for you to step on it.",
    secondBiteAdvice: "⚠️ 4-Star Venom: 3-minute survival window. Want to wrap this up sooner? Go tap its tail again so the second dose gets released!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: You stepped on a leaf pile. The leaf pile bit you in 130 milliseconds." },
      { pct: 0.65, text: "Stage 2: Deep fang puncture. Local swelling and cold numbness creeping upward." },
      { pct: 0.40, text: "Stage 3: Motor nerve transmission blocked. Reflexes: None." },
      { pct: 0.15, text: "Stage 4: Complete respiratory paralysis. Time to count your sins." },
      { pct: 0.03, text: "Stage 5: It is in the name: DEATH Adder. What did you expect?" }
    ],
    avatarColor: "#616161"
  },
  {
    id: "beaked_sea_snake",
    name: "Hook-Nosed Sea Snake",
    scientificName: "Hydrophis schistosus",
    nickname: "The Fisherman's Nightmare",
    primaryColor: "grey",
    colorCategory: "grey",
    colorDescription: "Uniform greyish-slate with subtle darker crossbands and downward hooked beak",
    spot: "water",
    spotDescription: "Muddy estuaries, river mouths, fishing trawler nets, shallow mangrove channels",
    region: "Arabian Sea, Bay of Bengal, Southeast Asian coasts",
    ld50: "0.11 mg/kg (Causes >90% of all fatal sea snake bites)",
    venomType: "Potent Myotoxin destroying skeletal muscle tissue",
    threatLevel: 4,
    countdownSeconds: 180,
    clinicalSurvival: "1 to 3 hours without specialized sea snake antivenom",
    sarcasticQuote: "Responsible for almost every sea snake fatality in Asian fishing communities because it gets tangled in nets and bites through trousers.",
    sarcasticAdvice: "Untangling a mystery wriggling net in the dark: 0/10 stars on TripAdvisor.",
    secondBiteAdvice: "⚠️ 4-Star Pelagic Toxins: Taking 3 minutes? Stick your foot back into the trawler net for a refill so the venom works faster!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Punctured through your deck shoes. Ow, what was that crab?" },
      { pct: 0.65, text: "Stage 2: Intense whole-body myalgia. Moving your fingers feels like lifting bricks." },
      { pct: 0.40, text: "Stage 3: Massive myoglobinuria. Kidneys surrender unconditionally." },
      { pct: 0.15, text: "Stage 4: Complete respiratory paralysis." },
      { pct: 0.03, text: "Stage 5: The fish got away. And so did your soul." }
    ],
    avatarColor: "#78909c"
  },
  {
    id: "mojave_rattlesnake",
    name: "Mojave Rattlesnake",
    scientificName: "Crotalus scutulatus",
    nickname: "Mojave Green Mean Machine",
    primaryColor: "green",
    colorCategory: "green",
    colorDescription: "Greenish-brown to olive-tan with white diamond outlines and wide white tail bands",
    spot: "desert",
    spotDescription: "Creosote bush scrub, Joshua tree desert plains, rocky washes in the American Southwest",
    region: "Southwestern USA & Central Mexico",
    ld50: "0.24 mg/kg (Contains deadly Mojave Toxin A neurotoxin)",
    venomType: "Biphasic: Classic tissue-rotting Hemotoxin + Lethal Neurotoxin",
    threatLevel: 4,
    countdownSeconds: 180,
    clinicalSurvival: "30 to 60 minutes before neurotoxic respiratory paralysis takes over",
    sarcasticQuote: "Unlike other rattlesnakes that just destroy tissue, the Mojave also paralyzes your lungs. Two for the price of one!",
    sarcasticAdvice: "Did you hear the rattle and decide to lean in for a selfie? Congratulations, you played yourself.",
    secondBiteAdvice: "⚠️ 4-Star Mojave Toxin: Waiting 3 minutes is tedious. Offer your other hand to the rattlesnake so the second payload gets delivered!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Rattle buzzes! Fang puncture. Oh it is just a normal rattler... wait." },
      { pct: 0.65, text: "Stage 2: Mojave Toxin A enters motor nerve endings. Vision starts doubling." },
      { pct: 0.40, text: "Stage 3: Difficulty breathing combined with local tissue swelling." },
      { pct: 0.15, text: "Stage 4: Complete diaphragm failure. Tell the cactus goodbye." },
      { pct: 0.03, text: "Stage 5: The desert claims another tourist." }
    ],
    avatarColor: "#558b2f"
  },
  {
    id: "fer_de_lance",
    name: "Fer-de-Lance (Terciopelo)",
    scientificName: "Bothrops asper",
    nickname: "The Rainforest Blender",
    primaryColor: "brown",
    colorCategory: "brown",
    colorDescription: "Dark brown or grey-black with pale yellow/cream X-shaped geometric markings",
    spot: "grass",
    spotDescription: "Coffee and banana plantations, rainforest floor leaf litter, near human settlements",
    region: "Central America & Northern South America",
    ld50: "1.1 mg/kg (Massive venom yield: 400-800 mg injected per bite)",
    venomType: "Catastrophic Cytotoxin, Hemorrhagin, Tissue-necrotizing enzymes",
    threatLevel: 4,
    countdownSeconds: 180,
    clinicalSurvival: "Massive localized tissue rotting within hours; fatal shock in 30-60 mins",
    sarcasticQuote: "It does not just bite you; it digests you from the inside out while you are still standing.",
    sarcasticAdvice: "Avoid walking through Costa Rican plantations at night in sandals. This is not negotiable.",
    secondBiteAdvice: "⚠️ 4-Star Necrosis: It gave you 3 minutes to admire your dissolving shin. Step closer for bite #2 to expedite the liquefaction!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Burning pain. Your leg feels like it was hit by a blowtorch." },
      { pct: 0.65, text: "Stage 2: Rapid black blistering and localized gangrene. Graphic content warning." },
      { pct: 0.40, text: "Stage 3: Massive drop in systemic blood pressure. Cardiogenic shock." },
      { pct: 0.15, text: "Stage 4: Internal bleeding into abdominal cavity." },
      { pct: 0.03, text: "Stage 5: Say hello to the Mayan underworld." }
    ],
    avatarColor: "#4e342e"
  },
  {
    id: "south_american_bushmaster",
    name: "South American Bushmaster",
    scientificName: "Lachesis muta",
    nickname: "The 12-Foot Jungle Tank",
    primaryColor: "yellow",
    colorCategory: "yellow",
    colorDescription: "Pale yellow, reddish-orange with bold black diamond-shaped saddles",
    spot: "tree",
    spotDescription: "Primary undisturbed Amazonian rainforest, hollow logs, tree buttress roots",
    region: "Amazon Basin, Northern South America",
    ld50: "1.5 mg/kg (Largest pit viper on Earth; can inject up to 1,000 mg of venom)",
    venomType: "Kallikrein-like enzymes causing vagal shock and profound hypotension",
    threatLevel: 4,
    countdownSeconds: 180,
    clinicalSurvival: "20 to 45 minutes before circulatory collapse and cardiac arrest",
    sarcasticQuote: "It is 12 feet of muscular fury hiding behind a mahogany root. If it strikes, it delivers enough venom to dissolve a mid-sized sedan.",
    sarcasticAdvice: "If you encounter a viper as thick as a firehose in the Amazon, you are officially outside the warranty zone of human medicine.",
    secondBiteAdvice: "⚠️ 4-Star Bushmaster: 3-minute timer in effect. For immediate service, poke the 12-foot tank again to extract the remaining poison!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Hit with the force of a baseball bat. Two 3cm holes." },
      { pct: 0.65, text: "Stage 2: Immediate vagal bradycardia. Your heart slows to a crawl." },
      { pct: 0.40, text: "Stage 3: Profuse cold sweating and irreversible blood pressure crash." },
      { pct: 0.15, text: "Stage 4: Total cardiovascular collapse. Darkness envelops the canopy." },
      { pct: 0.03, text: "Stage 5: The jungle never forgives." }
    ],
    avatarColor: "#ff8f00"
  },
  {
    id: "forest_cobra",
    name: "Forest Cobra (Black Cobra)",
    scientificName: "Naja melanoleuca",
    nickname: "The Glossy 10-Foot Nightmare",
    primaryColor: "black",
    colorCategory: "black",
    colorDescription: "Glossy pitch black body with bright cream/yellow chin and neck bands",
    spot: "water",
    spotDescription: "Tropical riverbanks, swamps, forest clearings, high canopies, mangrove roots",
    region: "Central & Western Sub-Saharan Africa",
    ld50: "0.22 mg/kg (Largest true cobra species, highly aquatic and aggressive)",
    venomType: "Postsynaptic Neurotoxins with massive volume yield",
    threatLevel: 4,
    countdownSeconds: 180,
    clinicalSurvival: "30 to 60 minutes before complete respiratory cessation",
    sarcasticQuote: "It can swim like an otter, climb trees like a monkey, stands 10 feet long, and carries enough neurotoxin to shut down a stadium.",
    sarcasticAdvice: "There is no terrain where you are safe from this snake: land, water, or trees. Your only hope was staying at home.",
    secondBiteAdvice: "⚠️ 4-Star Black Cobra: Why wait 3 minutes? Shake hands with this 10-foot reptile again so the second dose releases promptly!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: A 9-foot glossy black cobra flares a huge narrow hood." },
      { pct: 0.65, text: "Stage 2: Neurotoxins bind to nicotinic acetylcholine receptors. Weakness starts." },
      { pct: 0.40, text: "Stage 3: Complete inability to speak, swallow, or keep eyes open." },
      { pct: 0.15, text: "Stage 4: Asphyxiation due to total intercostal muscle paralysis." },
      { pct: 0.03, text: "Stage 5: Forest darkness wins." }
    ],
    avatarColor: "#121212"
  },
  {
    id: "caspian_cobra",
    name: "Caspian Cobra (Oxus Cobra)",
    scientificName: "Naja oxiana",
    nickname: "The Central Asian Widowmaker",
    primaryColor: "brown",
    colorCategory: "brown",
    colorDescription: "Uniform light chocolate brown to yellowish-ochre with no hood markings",
    spot: "rocks",
    spotDescription: "Rocky hillsides, ruins, irrigation canals, arid scrublands",
    region: "Central Asia (Iran, Afghanistan, Pakistan, Uzbekistan)",
    ld50: "0.21 mg/kg (The most toxic true cobra in the entire world)",
    venomType: "Extremely concentrated postsynaptic neurotoxin + cytotoxin",
    threatLevel: 4,
    countdownSeconds: 180,
    clinicalSurvival: "30 to 45 minutes; untreated mortality rate exceeds 80%",
    sarcasticQuote: "Most cobras have an LD50 around 0.5 mg/kg. The Caspian cobra looked at that and said I can do twice the damage with zero flair.",
    sarcasticAdvice: "No fancy spectacles on its hood. It does not need marketing when its venom is pure laboratory-grade murder.",
    secondBiteAdvice: "⚠️ 4-Star Widowmaker: 3 minutes remaining. If that feels too sluggish, let it strike once more to unload the reserve poison!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Plain brown cobra rears up in ancient ruins. Quick double strike." },
      { pct: 0.65, text: "Stage 2: Rapid onset ptosis and severe localized tissue necrosis." },
      { pct: 0.40, text: "Stage 3: Total respiratory muscle paralysis setting in fast." },
      { pct: 0.15, text: "Stage 4: Asphyxiation while staring at archaeological ruins." },
      { pct: 0.03, text: "Stage 5: You are now part of ancient history." }
    ],
    avatarColor: "#5d4037"
  },
  {
    id: "south_american_rattlesnake",
    name: "South American Rattlesnake (Cascavel)",
    scientificName: "Crotalus durissus",
    nickname: "The Blindness Bringer",
    primaryColor: "brown",
    colorCategory: "brown",
    colorDescription: "Yellowish-brown with prominent dark rhombic diamond markings and white edges",
    spot: "desert",
    spotDescription: "Dry savannah grasslands, caatinga thorny scrub, rocky outcrops",
    region: "South America (Brazil, Venezuela, Colombia, Argentina)",
    ld50: "0.15 mg/kg (Contains devastating neurotoxin Crotroxin)",
    venomType: "Crotroxin & Convulxin causing neuro-paralysis and myonecrosis",
    threatLevel: 4,
    countdownSeconds: 180,
    clinicalSurvival: "1 to 2 hours; causes unique neck muscle paralysis (broken neck symptom)",
    sarcasticQuote: "Its venom paralyzes your neck muscles so severely your head flops backwards like a broken doll.",
    sarcasticAdvice: "If you cannot hold your own head up after a snake bite, you are not having a good posture day.",
    secondBiteAdvice: "⚠️ 4-Star Rattler: Timer set to 3 minutes. Floppy neck taking too long? Get a second bite so the poison hits full velocity!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Rattle heard in dry scrub. Immediate bite to the shin." },
      { pct: 0.65, text: "Stage 2: Sudden acute blindness and loss of smell. Vision goes black." },
      { pct: 0.40, text: "Stage 3: Neck muscles completely collapse. Head flops limp like cooked pasta." },
      { pct: 0.15, text: "Stage 4: Systemic myonecrosis destroys kidneys." },
      { pct: 0.03, text: "Stage 5: The rattle rattles no more." }
    ],
    avatarColor: "#6d4c41"
  },
  {
    id: "golden_lancehead",
    name: "Golden Lancehead",
    scientificName: "Bothrops insularis",
    nickname: "The Island of Death Overlord",
    primaryColor: "yellow",
    colorCategory: "yellow",
    colorDescription: "Pale golden-yellow to brassy-tan with triangular spear-shaped head",
    spot: "tree",
    spotDescription: "Ilha da Queimada Grande (Snake Island), Brazil - exclusively in trees hunting migratory birds",
    region: "Snake Island (Ilha da Queimada Grande, off Brazilian coast)",
    ld50: "0.5 mg/kg (Evolutionarily optimized to dissolve bird flesh instantaneously)",
    venomType: "Fast-acting Hemotoxin & Cytotoxin that melts tissue to prevent prey flying away",
    threatLevel: 4,
    countdownSeconds: 180,
    clinicalSurvival: "30 to 60 minutes; melts tissue five times faster than mainland lanceheads",
    sarcasticQuote: "Lives on an island so infested with deadly vipers the Brazilian Navy officially banned all humans from stepping foot on it. How did you get there?!",
    sarcasticAdvice: "You literally had to hire an illegal boat to trespass on the worlds most forbidden death island to get bitten. You earned this Darwin Award.",
    secondBiteAdvice: "⚠️ 4-Star Snake Island Special: 3 minutes remaining. You are on an island with 4,000 vipers; just lean on the next branch for bite #2!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: You bypassed military naval blockades to visit Snake Island. Brilliant." },
      { pct: 0.65, text: "Stage 2: Flesh-melting venom designed to drop birds mid-air begins dissolving capillaries." },
      { pct: 0.40, text: "Stage 3: Brain hemorrhage and renal failure within record time." },
      { pct: 0.15, text: "Stage 4: The Brazilian Navy is not coming to save you." },
      { pct: 0.03, text: "Stage 5: Golden Lancehead: King of the Forbidden Island." }
    ],
    avatarColor: "#fbc02d"
  },

  // ==================== 3-STAR DEADLY SNAKES (5 MINUTES / 300 SECONDS TO DIE) ====================
  {
    id: "yellow_bellied_sea_snake",
    name: "Yellow-Bellied Sea Snake",
    scientificName: "Hydrophis platurus",
    nickname: "The Floating Bumblebee of Death",
    primaryColor: "yellow",
    colorCategory: "yellow",
    colorDescription: "Pitch black dorsal side sharply divided from a vibrant canary yellow belly",
    spot: "water",
    spotDescription: "Floating in pelagic slicks, kelp drift lines, washed up on beaches",
    region: "Pacific and Indian Oceans (entire tropical belt)",
    ld50: "0.067 mg/kg (Extreme pelagic toxicity)",
    venomType: "Potent Myotoxin & Neurotoxin (kidney-melting breakdown)",
    threatLevel: 3,
    countdownSeconds: 300,
    clinicalSurvival: "1 to 2 hours of systemic muscle collapse",
    sarcasticQuote: "It looks like a floating two-tone ribbon. Children love picking them up on beaches, which is a fantastic way to traumatize a family vacation.",
    sarcasticAdvice: "If a sea creature looks like high-visibility construction tape, that is natures way of saying DO NOT TOUCH.",
    secondBiteAdvice: "⚠️ 3-Star Mild Envenomation: Taking a whole 5 minutes to die? That is embarrassing. Let it bite you one more time so the rest of the poison gets released!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Picked up a cool looking stick in the tide pool. Stick had teeth." },
      { pct: 0.65, text: "Stage 2: Generalized body aches and intense joint rigidity." },
      { pct: 0.40, text: "Stage 3: Kidneys clogging with destroyed muscle proteins." },
      { pct: 0.15, text: "Stage 4: Breathing is now a relic of the past." },
      { pct: 0.03, text: "Stage 5: Beach vacation officially canceled." }
    ],
    avatarColor: "#fdd835"
  },
  {
    id: "jararaca",
    name: "Jararaca",
    scientificName: "Bothrops jararaca",
    nickname: "The Blood Pressure Demolisher",
    primaryColor: "brown",
    colorCategory: "brown",
    colorDescription: "Olive-brown to grey with dark inverted-trapezoid or saddle markings",
    spot: "grass",
    spotDescription: "Manioc plantations, Atlantic coastal forest edges, piles of rotting timber",
    region: "Southeastern Brazil, Paraguay, Northern Argentina",
    ld50: "1.1 mg/kg (Origin of modern ACE inhibitors thanks to its blood-pressure dropping toxin)",
    venomType: "Bradykinin-potentiating peptides, procoagulants, extensive necrosis",
    threatLevel: 3,
    countdownSeconds: 300,
    clinicalSurvival: "1 to 3 hours of severe hemorrhagic shock without medical intervention",
    sarcasticQuote: "Scientists used its venom to invent blood pressure medications. Too bad its bite gives you an overdose in 5 seconds flat.",
    sarcasticAdvice: "Your blood pressure is now zero over zero. The good news: hypertension is cured!",
    secondBiteAdvice: "⚠️ 3-Star Slow Burn: 5 whole minutes! Who has that kind of time? Offer your other ankle to the Jararaca so the remaining poison discharges properly!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Sharp fangs connect with your calf. Immediate throbbing agony." },
      { pct: 0.65, text: "Stage 2: Bradykinin surge drops your systolic pressure through the floorboards." },
      { pct: 0.40, text: "Stage 3: Uncontrollable oozing from the bite site and eyes." },
      { pct: 0.15, text: "Stage 4: Brain perfusion has ceased. Good night." },
      { pct: 0.03, text: "Stage 5: At least your hypertension is gone!" }
    ],
    avatarColor: "#5d4037"
  },
  {
    id: "puff_adder",
    name: "Puff Adder",
    scientificName: "Bitis arietans",
    nickname: "The Grumpy Landmine",
    primaryColor: "brown",
    colorCategory: "brown",
    colorDescription: "Dull yellow-brown to dark sand with bold yellow chevron (V-shaped) dorsal markings",
    spot: "rocks",
    spotDescription: "Basking on warm dirt roads at night, savannah footpaths, dry rocky hillsides",
    region: "Sub-Saharan Africa & Southwestern Arabia",
    ld50: "1.0 mg/kg (Causes more fatal bites in Africa than any other viper)",
    venomType: "Extremely destructive Cytotoxin & Hemotoxin causing massive necrosis",
    threatLevel: 3,
    countdownSeconds: 300,
    clinicalSurvival: "Severe shock within 30 minutes; extensive gangrene requiring amputation",
    sarcasticQuote: "Does not move when approached. Simply puffs up, hisses like an angry tire, and explodes forward at lightning speed.",
    sarcasticAdvice: "You did not see it because it looks exactly like dirt. That is not your fault, but the gangrene does not care whose fault it was.",
    secondBiteAdvice: "⚠️ 3-Star Sluggish Cytotoxin: 5 minutes is amateur hour. Tap the grumpy landmine again to get the full reserve dosage released!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Loud pneumatic hiss followed by instantaneous puncture." },
      { pct: 0.65, text: "Stage 2: Massive rapid edema. Your limb swells to twice its normal girth." },
      { pct: 0.40, text: "Stage 3: Deep compartment syndrome and flesh necrosis." },
      { pct: 0.15, text: "Stage 4: Severe hypotension and multiorgan failure." },
      { pct: 0.03, text: "Stage 5: Puffed away." }
    ],
    avatarColor: "#8d6e63"
  },
  {
    id: "indian_cobra",
    name: "Indian Spectacled Cobra",
    scientificName: "Naja naja",
    nickname: "The Spectacled Showstopper",
    primaryColor: "brown",
    colorCategory: "brown",
    colorDescription: "Warm brown, tan, or black with iconic white-and-black spectacle pattern on rear of hood",
    spot: "bed",
    spotDescription: "Inside rural dwellings, grain stores, under beds, agricultural field edges",
    region: "Indian Subcontinent (India, Pakistan, Sri Lanka, Bangladesh)",
    ld50: "0.56 mg/kg (Member of the dreaded Big Four of India)",
    venomType: "Postsynaptic Neurotoxin, Cardiotoxin, and localized Cytotoxin",
    threatLevel: 3,
    countdownSeconds: 300,
    clinicalSurvival: "30 to 60 minutes before respiratory arrest without antivenom",
    sarcasticQuote: "Wears glasses on the back of its hood to mock your inability to see it hiding behind your cupboard.",
    sarcasticAdvice: "Do not attempt snake charming unless you have a professional flute and zero desire to live.",
    secondBiteAdvice: "⚠️ 3-Star Cobra Rating: 5 minutes to expire! If you want the full Bollywood climax, let it bite you one more time so all the poison gets released!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Hood flares, spectacle pattern visible. Sharp bite to ankle." },
      { pct: 0.65, text: "Stage 2: Localized burning, swelling, and severe tissue necrosis." },
      { pct: 0.40, text: "Stage 3: Progressive flaccid paralysis spreading from head downwards." },
      { pct: 0.15, text: "Stage 4: Respiratory arrest imminent. No more oxygen for you." },
      { pct: 0.03, text: "Stage 5: The show has ended. Curtains close." }
    ],
    avatarColor: "#5d4037"
  },
  {
    id: "common_krait",
    name: "Common Krait",
    scientificName: "Bungarus caeruleus",
    nickname: "The Midnight Cuddle Monster",
    primaryColor: "black",
    colorCategory: "black",
    colorDescription: "Deep shiny steel-blue to jet black with thin paired white cross-stripes",
    spot: "bed",
    spotDescription: "Crawling into rural huts at 3 AM, sleeping mats, under pillows, inside shoes",
    region: "South Asia (India, Pakistan, Nepal, Sri Lanka)",
    ld50: "0.32 mg/kg (Deadliest night-biter in the Big Four)",
    venomType: "Presynaptic & Postsynaptic Neurotoxins that destroy nerve endings",
    threatLevel: 3,
    countdownSeconds: 300,
    clinicalSurvival: "1 to 4 hours; bites are completely painless while victim is asleep",
    sarcasticQuote: "It crawls into your bed at 3 AM because your body heat is cozy, bites you painlessly like a mosquito, and lets you sleep forever.",
    sarcasticAdvice: "Did you feel a tiny prick on your foot in bed at 3 AM and think probably a mosquito? Rest in peace, buddy.",
    secondBiteAdvice: "⚠️ 3-Star Nocturnal Stealth: 5-minute countdown. Did not feel enough poison? Invite it back under the duvet for round two so it releases properly!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Did something pinch my toe under the blanket? Back to sleep..." },
      { pct: 0.65, text: "Stage 2: Wake up at 5 AM with excruciating abdominal cramps and locked jaw." },
      { pct: 0.40, text: "Stage 3: Total paralysis. Cannot speak or call out for help." },
      { pct: 0.15, text: "Stage 4: Diaphragm fails completely. Still fully conscious inside your skull." },
      { pct: 0.03, text: "Stage 5: The midnight cuddle was fatal." }
    ],
    avatarColor: "#1a237e"
  },
  {
    id: "malayan_pit_viper",
    name: "Malayan Pit Viper",
    scientificName: "Calloselasma rhodostoma",
    nickname: "The Rubber Tree Amputator",
    primaryColor: "brown",
    colorCategory: "brown",
    colorDescription: "Reddish-brown to pinkish-tan with dark brown triangular lateral markings",
    spot: "grass",
    spotDescription: "Rubber plantations, bamboo groves, roadside ditches, rotting fallen leaves",
    region: "Southeast Asia (Thailand, Malaysia, Vietnam, Java)",
    ld50: "0.30 mg/kg (Major cause of amputations and morbidity in SE Asia)",
    venomType: "Thrombin-like enzyme (Ancrod) causing massive fibrinogen depletion and gangrene",
    threatLevel: 3,
    countdownSeconds: 300,
    clinicalSurvival: "Severe coagulopathy within hours; massive local tissue rot",
    sarcasticQuote: "It refuses to move even when you are 2 inches away. It waits until your foot touches its face, then turns your leg into soup.",
    sarcasticAdvice: "If you work in a Southeast Asian rubber plantation, buy heavy boots. Better yet, get an office job.",
    secondBiteAdvice: "⚠️ 3-Star Pit Viper: A 5-minute agonizing wait. If you want the gangrene to hurry up, stomp near it again so the rest of the venom discharges!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Stepped directly on a pile of leaves. Leaves bite back violently." },
      { pct: 0.65, text: "Stage 2: Blood refuses to clot. Fibrinogen plummets to undetectable levels." },
      { pct: 0.40, text: "Stage 3: Extreme localized swelling and gangrenous bullae formation." },
      { pct: 0.15, text: "Stage 4: Sepsis and kidney failure from tissue breakdown." },
      { pct: 0.03, text: "Stage 5: Plantations: 0, Viper: 1." }
    ],
    avatarColor: "#795548"
  },
  {
    id: "green_mamba",
    name: "Eastern Green Mamba",
    scientificName: "Dendroaspis angusticeps",
    nickname: "The Emerald Assassin",
    primaryColor: "green",
    colorCategory: "green",
    colorDescription: "Brilliant glossy emerald green with bright lime underbelly and slender whip body",
    spot: "tree",
    spotDescription: "Coastal tea plantations, mango trees, coastal thicket canopies, thatched roofs",
    region: "Eastern Sub-Saharan Africa",
    ld50: "0.40 mg/kg (High potency neurotoxin)",
    venomType: "Fasciculins (AChE inhibitors) & Cardiotoxins",
    threatLevel: 3,
    countdownSeconds: 300,
    clinicalSurvival: "30 to 90 minutes untreated; rapid neuromuscular paralysis",
    sarcasticQuote: "It spends 99% of its life in trees pretending to be a leafy vine. You grabbed the vine.",
    sarcasticAdvice: "Picking mangoes without looking? Hope that mango was worth your remaining 45 seconds on planet Earth.",
    secondBiteAdvice: "⚠️ 3-Star Green Mamba: 5 minutes to expire! Unlike its Black Mamba cousin, this one is taking its sweet time. Shake the branch to get bitten once more for extra poison!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Reached for a fresh fruit in the tree. Grabbed 6 feet of emerald lightning." },
      { pct: 0.65, text: "Stage 2: Intense muscle fasciculations (twitching like a malfunctioning robot)." },
      { pct: 0.40, text: "Stage 3: Salivation, sweating, and rapid heart deceleration." },
      { pct: 0.15, text: "Stage 4: Complete respiratory motor collapse." },
      { pct: 0.03, text: "Stage 5: That was your last mango." }
    ],
    avatarColor: "#2e7d32"
  },
  {
    id: "red_bellied_black_snake",
    name: "Red-Bellied Black Snake",
    scientificName: "Pseudechis porphyriacus",
    nickname: "The Goth Danger Noodle",
    primaryColor: "black",
    colorCategory: "black",
    colorDescription: "Glossy jet black dorsum with vibrant crimson or hot-pink lower flanks and belly",
    spot: "water",
    spotDescription: "Creeks, marshes, backyard swimming pools, garden compost, wetlands",
    region: "Eastern Australia",
    ld50: "2.5 mg/kg (Commonly encountered, highly venomous but rare fatal outcomes today with antivenom)",
    venomType: "Myotoxins, Hemolysins, Coagulants, and mild Neurotoxins",
    threatLevel: 3,
    countdownSeconds: 300,
    clinicalSurvival: "Hours of agony, loss of smell, and muscle death without antivenom",
    sarcasticQuote: "Looks like it was designed by an edgy teenage fashion designer: glossy black leather with hot-pink trim.",
    sarcasticAdvice: "Found in Australian backyards and suburban swimming pools. Because of course it wants to swim with you.",
    secondBiteAdvice: "⚠️ 3-Star Goth Noodle: 5 minutes of mild muscle aches. Feeling underwhelmed? Jump back in the pool and ask for a second bite so the poison kicks in faster!",
    sarcasticStages: [
      { pct: 0.90, text: "Stage 1: Look at those gorgeous pink scales! (Bite delivered to hand)." },
      { pct: 0.65, text: "Stage 2: Complete and permanent loss of your sense of smell (anosmia)." },
      { pct: 0.40, text: "Stage 3: Severe nausea, abdominal spasms, and localized swelling." },
      { pct: 0.15, text: "Stage 4: Muscle breakdown proteins flooding bloodstream." },
      { pct: 0.03, text: "Stage 5: The goth noodle claimed your sanity." }
    ],
    avatarColor: "#212121"
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = SNAKES_DATA;
}